### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by kaneko-joei** [kaneko-joei/protospace-31577#1]
https://protospace-31577.herokuapp.com/

**Comment by kuroshio214** [comment]
kaneko-joeiさん、ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所が1点ございました。
以下のご確認をお願いします！

[修正依頼箇所]
①編集ページに遷移すると、編集できる項目が見当たらない
　→編集項目を表示させ、必要な情報を入力すると、プロトタイプが編集でき、詳細ページへ遷移するようにしましょう

ProtoSpace完成までもう少しです！
引き続き頑張りましょう！

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7
